version: '4.0'
services:

  server:
    image: backend
    container_name: 'cloud-storage'
    build: ./
    ports:
      - "5050:5050"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgres://database:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_LIQUIBASE_URL: jdbc:postgres://database:5432/postgres
      SPRING_LIQUIBASE_USER: postgres
      SPRING_LIQUIBASE_PASSWORD: postgres

  database:
    image: postgres
    container_name: 'cloud-storage-diplom'
    volumes:
      -  /var/lib/postgres:/var/lib/postgres
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_ROOT_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    ports:
      - "5432:5432"